TRADE_DATA = {
"Id": "number",
"ClientId": "string",  # changed from ("string", "optional")
"AccountId": "number",
"Type": "string",
"InitialType": "string",  # changed from ("string", "optional")
"Side": "string",
"Status": "string",
"Symbol": "string",  # changed from ("string", "optional")
"SymbolPrecision": "number",
"StopPrice": "number",
"Price": "number",
"CurrentPrice": "number",
"InitialAmount": "number",
"RemainingAmount": "number",
"FilledAmount": "number",
"MaxVisibleAmount": "number",
"StopLoss": "number",
"TakeProfit": "number",
"Margin": "number",
"Profit": "number",
"Commission": "number",
"AgentCommission": "number",
"Swap": "number",
"ImmediateOrCancel": "bool",
"MarketWithSlippage": "bool",
"FillOrKill": "bool",
"OneCancelsTheOther": "bool",
"Created": "number",
"Expired": "number",
"Modified": "number",
"Filled": "number",
"PositionCreated": "number",
"Comment": "string",  # changed from ("string", "optional")
"ClientApp": "string",  # changed from ("string", "optional")
"Slippage": "number",
"Rebate": "number",
"RelatedTradeId": "number",
"ContingentOrder": "bool",
"TriggerType": "string",
"TriggerTime": "number",
"OrderIdTriggeredBy": "number",
}